include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    must_be_immutable: ignore
    camel_case_types: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
